/**
 * generate-config.js
 * Reads TG_API_ID and TG_API_HASH from .env and writes www/js/config.js
 * Run before every build: node scripts/generate-config.js
 * This file is safe to commit. .env is NOT committed (gitignored).
 */

const fs = require('fs');
const path = require('path');

// Load .env manually (no external packages needed)
const envPath = path.resolve(__dirname, '../.env');
if (!fs.existsSync(envPath)) {
  console.error('[generate-config] ERROR: .env file not found at', envPath);
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf-8');
const env = {};
envContent.split('\n').forEach(line => {
  const [key, ...rest] = line.split('=');
  if (key && rest.length) env[key.trim()] = rest.join('=').trim().replace(/^"|"$/g, '');
});

const apiId   = env['TG_API_ID'];
const apiHash = env['TG_API_HASH'];

if (!apiId || !apiHash) {
  console.error('[generate-config] ERROR: TG_API_ID or TG_API_HASH missing from .env');
  process.exit(1);
}

const output = `// Auto-generated App Configuration — DO NOT EDIT MANUALLY
// Generated by: node scripts/generate-config.js
window.TG_API_ID   = '${apiId}';
window.TG_API_HASH = '${apiHash}';
`;

const outPath = path.resolve(__dirname, '../web/js/config.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`[generate-config] ✅ config.js written with API_ID=${apiId}`);
